### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by zacvoge** [rhysbryant/goprinterrelay#5]
sorry to be asking so many questions but now when i write to the json file to change the usb is says permission denied

**Comment by rhysbryant** [comment]
Sudo nano config.json

**Comment by zacvoge** [comment]
![image](https://user-images.githubusercontent.com/26075832/69109910-176a0000-0a47-11ea-948b-045b336e94bb.png)

**Comment by zacvoge** [comment]
This is what i get

**Comment by zacvoge** [comment]
could it be because its running?

**Comment by rhysbryant** [comment]
Likely not but I would recommend stopping it before editing the
configuration anyway

**Comment by zacvoge** [comment]
whats the command to stop it i have been trying to find it

**Comment by zacvoge** [comment]
well its still not allowing me to edit it even after stopping

**Comment by zacvoge** [comment]
![image](https://user-images.githubusercontent.com/26075832/69113776-fb1f9080-0a51-11ea-890f-9e1a181c4dd8.png)

**Comment by zacvoge** [comment]
you have the file permissions set to - instead it needs to be +

**Comment by zacvoge** [comment]
its telling me the owner is 3434 and the group is set to 3434

**Comment by rhysbryant** [comment]
Sudo chown pi:pi config.json then try editing it

**Comment by zacvoge** [comment]
![image](https://user-images.githubusercontent.com/26075832/69114884-c19c5480-0a54-11ea-8acb-8963e3f84b10.png)

**Comment by zacvoge** [comment]
here is what i got

**Comment by zacvoge** [comment]
i just ran it again because i saw that i didnt just paste what u told me i pasted the whole sentence but it said operation  not permitted

**Comment by zacvoge** [comment]
i think i see whats wrong here let me re do this real fast

**Comment by zacvoge** [comment]
so instead of running it through the root i ran it through the desktop and it connected but now i cant get the camera to work

**Comment by zacvoge** [comment]
okay i got it thanks for your help
